use("opticaCulAmpolla");

db.getCollection("ulleres").insertOne({
  brand: "Brand",
  frame: "Metallic",
  lens_graduation: {
    left: "1.5",
    right: "2.0",
  },
  frame_color: "Black",
  lens_color: {
    left: "Clear",
    right: "Clear",
  },
  price: 105.75,
  provider: {
    name: "Googles Associated SL",
    address: {
      street: "Entença",
      number: 45,
      floor: 2,
      door: "1",
      city: "Barcelona",
      postal_code: 12345,
      country: "Spain",
    },
    phone_number: "654789321",
    fax: "936669933",
    nif: "B12345678",
  },
  bought_by: [
    {
      name: "Client 1",
      address: {
        street: "789 Oak St",
        number: 12,
        floor: 4,
        door: 2,
        city: "City C",
        postal_code: 24680,
        country: "Country C",
      },
      email: "Client1@perez.com",
      phone_number: "1230984567",
      registered_since: "2022-01-10",
      recommended_by: null,
    },
    {
      name: "Client 2",
      address: {
        street: "345 Oak St",
        number: 12,
        floor: 4,
        door: 2,
        city: "City C",
        postal_code: 24680,
        country: "Country C",
      },
      email: "Client2@perez.com",
      phone_number: "1230984567",
      registered_since: "2022-01-10",
      recommended_by: null,
    },
    {
      name: "Client 3",
      address: {
        street: "753 Oak St",
        number: 12,
        floor: 4,
        door: 2,
        city: "City C",
        postal_code: 24680,
        country: "Country C",
      },
      email: "Client3@perez.com",
      phone_number: "1230984567",
      registered_since: "2022-01-10",
      recommended_by: null,
    },
  ],
  sold_by: {
    employee_name: "Employee 1",
    date: "2023-07-15T14:30:00Z",
  },
});
